# Lending Environment Simulation & Lender Evaluation Tool

# Data Cleaning Algorithm Validation

In [1]:
import numpy as np
import pandas as pd
from kasi.processing import category_maps as maps
from kasi.processing import data_processor as pc
from kasi.processing import dictionaries as dc
import glob

pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

input_path_clean = "../../data/processed/clean_data.csv"
input_path_original = "../../data/original/**"

In [2]:
paths = glob.glob(input_path_original)
dfc = pd.read_csv(input_path_clean)
dfo = pd.concat([pd.read_csv(f,names=range(0,38),header=0,low_memory=False) for f in paths],ignore_index = True)
print(dfo.shape,dfc.shape)
dfc.describe()

ValueError: No objects to concatenate

In [2]:
dfo.head()

NameError: name 'dfo' is not defined

In [3]:
df_comb = pd.concat([dfo,dfc], axis=1)
df = df_comb.sample(frac=0.1)

NameError: name 'dfo' is not defined

In [6]:
df[[2,'2',3,'3',4,'4',5,'5',6,'6',7,'7',8,'8',9,'9']]

                                2  2                  3  3              4  4                  5  5                        6  6                        7  7                        8  8               9  9
993                 Same / Pareil  2  Maybe / Peut-Ãªtre  2    More / Plus  1          Yes / Oui  3      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
8263                Same / Pareil  2          Yes / Oui  3  Same / Pareil  2          Yes / Oui  3  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
13907  Difficult / Plus difficile  1          Yes / Oui  3   Less / Moins  3           No / Non  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
12918        Easier / Plus facile  3          Yes / Oui  3  Same / Pareil  2          Yes / Oui  3      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
22923        Easier / Plus facile  3           No / Non  1  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3      Improve / AmÃ©liorÃ©e  1  Female / Femme  1
27414               Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2          Yes / Oui  3  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2    Male / Homme  2
7485                Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
7890   Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Worsen / DÃ©tÃ©riorÃ©e  3  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
3507   Difficult / Plus difficile  1           No / Non  1  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1  Female / Femme  1
785                 Same / Pareil  2  Maybe / Peut-Ãªtre  2   Less / Moins  3  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
6139   Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2    More / Plus  1  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
9367   Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Worsen / DÃ©tÃ©riorÃ©e  3  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
17523        Easier / Plus facile  3          Yes / Oui  3   Less / Moins  3          Yes / Oui  3      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
1114   Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2    More / Plus  1          Yes / Oui  3  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
23225  Difficult / Plus difficile  1          Yes / Oui  3  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1     Worsen / DÃ©tÃ©rioriÃ©e  3  Stay the same / La mÃªme  2    Male / Homme  2
13581  Difficult / Plus difficile  1           No / Non  1  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
1307                Same / Pareil  2          Yes / Oui  3  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
27348               Same / Pareil  2  Maybe / Peut-Ãªtre  2   Less / Moins  3           No / Non  1  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3  Stay the same / La mÃªme  2    Male / Homme  2
1614                Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
2669                Same / Pareil  2          Yes / Oui  3  Same / Pareil  2          Yes / Oui  3      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
24930  Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2          Yes / Oui  3  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
21375               Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
806                 Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
14791  Difficult / Plus difficile  1           No / Non  1   Less / Moins  3  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1  Female / Femme  1
23394  Difficult / Plus difficile  1          Yes / Oui  3    More / Plus  1  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
...                           ... ..                ... ..            ... ..                ... ..                      ... ..                      ... ..                      ... ..             ... ..
26582               Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
28454                         NaN  2                NaN  2            NaN  2                NaN  2                      NaN  2                      NaN  2                      NaN  2             NaN  2
5792                Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
24516  Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3    Male / Homme  2
19266                         NaN  2                NaN  2            NaN  2                NaN  2                      NaN  2                      NaN  2                      NaN  2  Female /Â Femme  1
13070  Difficult / Plus difficile  1          Yes / Oui  3    More / Plus  1          Yes / Oui  3      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
24215  Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2          Yes / Oui  3  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
20437  Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2    More / Plus  1  Maybe / Peut-Ãªtre  2      Worsen / DÃ©tÃ©riorÃ©e  3  Stay the same / La mÃªme  2      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
6457                Same / Pareil  2  Maybe / Peut-Ãªtre  2   Less / Moins  3          Yes / Oui  3  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
326                 Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Worsen / DÃ©tÃ©riorÃ©e  3  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2
23953  Difficult / Plus difficile  1          Yes / Oui  3    More / Plus  1          Yes / Oui  3      Worsen / DÃ©tÃ©riorÃ©e  3     Worsen / DÃ©tÃ©rioriÃ©e  3      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
14586        Easier / Plus facile  3           No / Non  1   Less / Moins  3           No / Non  1      Worsen / DÃ©tÃ©riorÃ©e  3     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3    Male / Homme  2
10733  Difficult / Plus difficile  1           No / Non  1   Less / Moins  3  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3  Female / Femme  1
28510                         NaN  2                NaN  2            NaN  2                NaN  2                      NaN  2                      NaN  2                      NaN  2             NaN  2
3630                Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
7001   Difficult / Plus difficile  1          Yes / Oui  3    More / Plus  1  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3  Female / Femme  1
9374   Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
10986  Difficult / Plus difficile  1           No / Non  1   Less / Moins  3           No / Non  1      Worsen / DÃ©tÃ©riorÃ©e  3     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3    Male / Homme  2
8051   Difficult / Plus difficile  1          Yes / Oui  3    More / Plus  1          Yes / Oui  3      Worsen / DÃ©tÃ©riorÃ©e  3     Worsen / DÃ©tÃ©rioriÃ©e  3      Worsen / DÃ©tÃ©riorÃ©e  3    Male / Homme  2
5481                Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2  Female / Femme  1
16589               Same / Pareil  2  Maybe / Peut-Ãªtre  2  Same / Pareil  2  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1    Male / Homme  2
23107        Easier / Plus facile  3  Maybe / Peut-Ãªtre  2   Less / Moins  3  Maybe / Peut-Ãªtre  2  Stay the same / La mÃªme  2     Worsen / DÃ©tÃ©rioriÃ©e  3  Stay the same / La mÃªme  2  Female / Femme  1
28864                         NaN  2                NaN  2            NaN  2                NaN  2                      NaN  2                      NaN  2                      NaN  2             NaN  2
17904  Difficult / Plus difficile  1  Maybe / Peut-Ãªtre  2    More / Plus  1           No / Non  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1      Improve / AmÃ©liorÃ©e  1  Female / Femme  1
25870               Same / Pareil  2          Yes / Oui  3    More / Plus  1  Maybe / Peut-Ãªtre  2      Improve / AmÃ©liorÃ©e  1  Stay the same / La mÃªme  2  Stay the same / La mÃªme  2    Male / Homme  2

[2938 rows x 16 columns]

In [13]:
## columns that participate in model training and scoe calculation
df[[14,'14',16,'16',18,'18',19,'19',20,'20',21,'21',22,'22',23,'23',24,'24',25,'25',26,'26',36,'36']]

                                                      14  14             16  16                                     18  18                                     19  19                                                 20  20                                                 21  21                                        22  22                                        23  23                                        24  24                                                 25  25                                                 26  26            36  36
16462                                                NaN   0          Kenya   4                        Once / Une fois   3                             1000-20000   3         Business colleagues / Collegues de travail   3    At least 1 month but than 3 months /Â 1 - 2 mois   2   Most of the time /Â La majoritÃ© du temps   2  About half the time /Â La moitiÃ© du temps   3  About half the time /Â La moitiÃ© du temps   3         At least 9 out of 10 times / 9 fois sur 10   2                                                NaN   2           NaN   8
28158                                                NaN   0       Cameroon   1                        Once / Une fois   3                                  75000   3  Family /Â La famille, Friends /Â Les amis, Busin...   2  At least 6 months but less than 12 months / 6 ...   4  About half the time /Â La moitiÃ© du temps   3  About half the time /Â La moitiÃ© du temps   3  About half the time /Â La moitiÃ© du temps   3  At least 7-8 out of 10 times / Au moins 7-8 fo...   3  Personal or family expenses (Health, education...   1           NaN   8
134      I am not a student / Je ne suis pas un Ã©tudiant   2          Ghana   3                                   Once   3                           Less than 90   1                                             Family   1               Never - I don't expect to get repaid   6                                     Never   5                                     Never   5                                     Never   5                        Less than 5 out of 10 times   5  To pay for one-time or sudden expenses (Weddin...   2  Less than 5%   1
8192                                                 NaN   0          Ghana   3                                   Once   3                                    100   2                                      Micro finance   2                 At least 1 month but than 3 months   2                                     Never   5                       About half the time   3                                     Never   5                       At least 7-8 out of 10 times   3           Investment (commerce, merchandise, etc.)   3           NaN   8
18920                                                NaN   0          Kenya   4                        Once / Une fois   3       At least 1000 but less than 4000   2                                 Friends /Â Les amis   2    At least 1 month but than 3 months /Â 1 - 2 mois   2                    Occasionally / Souvent   4                    Occasionally / Souvent   4                    Occasionally / Souvent   4  At least 7-8 out of 10 times / Au moins 7-8 fo...   3                                                NaN   2           NaN   8
5181                                                 NaN   0        Nigeria   5                      More than 4 times   1  At least 31,001 but less than 160,000   3                                            Friends   2                                  Less than a month   1                                    Always   1                                    Always   1                                    Always   1                                         Every time   1    Personal or family expenses (Health, education)   1           NaN   8
26130                                                NaN   0       Cameroon   1                         Plus de 4 fois   1                Entre 59 001 et 290 000   2                                           Les amis   2                                    Moins d'un mois   1                      La majoritÃ© du temps   2                      La majoritÃ© du temps   2                        La moitiÃ© du temps   3                           Au moins 5-6 fois sur 10   4                            Investir dans un projet   3           NaN   8
1955   Post Graduate Degree / UniversitÃ© Niveau Maitr...   3       Tanzania   7                                   Once   3             Between 45,000 and 199,999   2                                             Family   1           At least 3 months but less than 6 months   3                          Most of the time   2                       About half the time   3                       About half the time   3                       At least 5-6 out of 10 times   4  To invest or cover business expenses (Merchand...   3  Less than 5%   1
25932                                                NaN   0       Cameroon   1                         Plus de 4 fois   1                Entre 59 001 et 290 000   2                                           Les amis   2                                         3 - 5 mois   3                                   Souvent   4                      La majoritÃ© du temps   2                                  Toujours   1                           Au moins 7-8 fois sur 10   3                            Investir dans un projet   3           NaN   8
5587                                                 NaN   0   South Africa   6                      Between 2-3 times   2       At least 1201 but less than 6400   3                                            Friends   2           At least 3 months but less than 6 months   3                              Occasionally   4                              Occasionally   4                       About half the time   3                       At least 7-8 out of 10 times   3    Personal or family expenses (Health, education)   1           NaN   8
10894                                                NaN   0          Kenya   4                      Between 2-3 times   2               Between 2,000 and 10,499   2                                            Friends   2            At least 1 month but less than 3 months   2                          Most of the time   2                                    Always   1                                    Always   1                         At least 9 out of 10 times   2    Personal or family expenses (Health, education)   1           NaN   8
25417                                                NaN   0  Cote d'Ivoire   2                                 Aucune   2                        Plus de 290 001   2                                           Les amis   2                                         1 - 2 mois   2                                  Toujours   1                                  Toujours   1                                   Souvent   4                           Au moins 5-6 fois sur 10   4                            Investir dans un projet   3           NaN   8
25865                                                NaN   0       Cameroon   1                      Entre 2 et 3 fois   2                 Entre 10 001 et 59 000   2                                           Les amis   2                                         1 - 2 mois   2                        La moitiÃ© du temps   3                      La majoritÃ© du temps   2                      La majoritÃ© du temps   2                           Au moins 7-8 fois sur 10   3                            Investir dans un projet   3           NaN   8
1030     I am not a student / Je ne suis pas un Ã©tudiant   2        Nigeria   5                      Between 2-3 times   2                      More than 160,001   4                                             Family   1           At least 3 months but less than 6 months   3                       About half the time   3                              Occasionally   4                          Most of the time   2                         At least 9 out of 10 times   2  To cover regular expenses (Rent, clothing, hom...   1  Less than 5%   1
28343                                                NaN   0       Cameroon   1                        Once / Une fois   3                                  20000   2                                 Friends /Â Les amis   2  At least 3 months but less than 6 months / 3 -...   3   Most of the time /Â La majoritÃ© du temps   2                         Always /Â Toujours   1  About half the time /Â La moitiÃ© du temps   3                       Every time / Toutes les fois   1  Personal or family expenses (Health, education...   1           NaN   8
15381                                                NaN   0          Ghana   3                         Never / Jamais   4                                     10   1         Business colleagues / Collegues de travail   3    At least 1 month but than 3 months /Â 1 - 2 mois   2                    Occasionally / Souvent   4                    Occasionally / Souvent   4                    Occasionally / Souvent   4  Less than 5 out of 10 times / Moins de 5 fois ...   5                                                NaN   2           NaN   8
28115                                                NaN   0       Cameroon   1  Between 2-3 times /Â Entre 2 et 3 fois   2                                 150000   3  Family /Â La famille, Business colleagues / Col...   2  At least 3 months but less than 6 months / 3 -...   3  About half the time /Â La moitiÃ© du temps   3   Most of the time /Â La majoritÃ© du temps   2   Most of the time /Â La majoritÃ© du temps   2  At least 7-8 out of 10 times / Au moins 7-8 fo...   3  Personal or family expenses (Health, education...   1           NaN   8
10048                                                NaN   0       Tanzania   7                      Between 2-3 times   2                                 600000   3                                             Family   1                                  Less than a month   1                                     Never   5                                     Never   5                          Most of the time   2                                         Every time   1           Investment (commerce, merchandise, etc.)   3           NaN   8
19292                                                NaN   0          Ghana   3                        Once / Une fois   3                      I am not in Kenya   2                                 Friends /Â Les amis   2    At least 1 month but than 3 months /Â 1 - 2 mois   2                    Occasionally / Souvent   4  About half the time / La moitiÃ© du temps   3  About half the time / La moitiÃ© du temps   3  At least 7-8 out of 10 times / Au moins 7-8 fo...   3                                                NaN   2           NaN   8
8919                                                 NaN   0          Kenya   4                      Between 2-3 times   2                                   2000   2                                            Friends   2                                  Less than a month   1                              Occasionally   4                                     Never   5                                     Never   5                       At least 5-6 out of 10 times   4    Personal or family expenses (Health, education)   1           NaN   8
7651                                                 NaN   0   South Africa   6                                   Once   3                          Less than 250   1                                            Friends   2            At least 1 month but less than 3 months   2                              Occasionally   4                              Occasionally   4                              Occasionally   4                                         Every time   1    Personal or family expenses (Health, education)   1           NaN   8
2366                                                 NaN   0          Ghana   3                      Between 2-3 times   2          At least 91 but less than 444   2                                            Friends   2            At least 1 month but less than 3 months   2                       About half the time   3                          Most of the time   2                          Most of the time   2                       At least 7-8 out of 10 times   3           Investment (commerce, merchandise, etc.)   3           NaN   8
25022                                                NaN   0       Cameroon   1                      Entre 2 et 3 fois   2                Entre 59 001 et 290 000   2                                           Les amis   2                                        6 - 11 mois   4                                   Souvent   4                                   Souvent   4                      La majoritÃ© du temps   2                           Au moins 5-6 fois sur 10   4                            Investir dans un projet   3           NaN   8
28010                                                NaN   0       Cameroon   1     More than 4 times / Plus de 4 fois   1                                 200000   3                                Family /Â La famille   1  At least 6 months but less than 12 months / 6 ...   4   Most of the time /Â La majoritÃ© du temps   2  About half the time /Â La moitiÃ© du temps   3  About half the time /Â La moitiÃ© du temps   3  At least 7-8 out of 10 times / Au moins 7-8 fo...   3  Investment (commerce, merchandise, etc.) / Inv...   3           NaN   8
22227                                                NaN   0  Cote d'Ivoire   2                      Entre 2 et 3 fois   2                Entre 59 001 et 290 000   2                                           Les amis   2                                         3 - 5 mois   3                        La moitiÃ© du temps   3                      La majoritÃ© du temps   2                      La majoritÃ© du temps   2                           Au moins 7-8 fois sur 10   3                            Investir dans un projet   3           NaN   8
...                                                  ...  ..            ...  ..                                    ...  ..                                    ...  ..                                                ...  ..                                                ...  ..                                       ...  ..                                       ...  ..                                       ...  ..                                                ...  ..                                                ...  ..           ...  ..
3128                                                 NaN   0        Nigeria   5                                   Once   3    At least 6,001 but less than 31,000   2                                             Family   1            At least 1 month but less than 3 months   2                                     Never   5                          Most of the time   2                          Most of the time   2                         At least 9 out of 10 times   2    Personal or family expenses (Health, education)   1           NaN   8
10865                                                NaN   0          Kenya   4                      Between 2-3 times   2               Between 2,000 and 10,499   2                                            Friends   2                                  Less than a month   1                                    Always   1                                    Always   1                                    Always   1                                         Every time   1    Personal or family expenses (Health, education)   1           NaN   8
415    Technical or Other college diploma / CollÃ¨ge t...   1          Kenya   4                      More than 4 times   1                        Less than 1,999   1                                Business colleagues   3           At least 3 months but less than 6 months   3                          Most of the time   2                       About half the time   3                       About half the time   3                         At least 9 out of 10 times   2  To pay for one-time or sudden expenses (Weddin...   2     10% - 20%   3
18366                                                NaN   0          Ghana   3                         Never / Jamais   4                      I am not in Kenya   2                                               none   2  At least 3 months but less than 6 months / 3 -...   3  About half the time /Â La moitiÃ© du temps   3                    Occasionally / Souvent   4                    Occasionally / Souvent   4  At least 5-6 out of 10 times / Au moins 5-6 fo...   4                                                NaN   2           NaN   8
8055                                                 NaN   0          Ghana   3                                  Never   4                                     50   1                                            Friends   2           At least 3 months but less than 6 months   3                              Occasionally   4                              Occasionally   4                              Occasionally   4                       At least 7-8 out of 10 times   3    Personal or family expenses (Health, education)   1           NaN   8
10053                                                NaN   0       Tanzania   7                      More than 4 times   1                                  50000   2                                            Friends   2                                  Less than a month   1                                     Never   5                                     Never   5                          Most of the time   2                                         Every time   1    Personal or family expenses (Health, education)   1           NaN   8
9854                                                 NaN   0   South Africa   6                      Between 2-3 times   2                                   1500   3                                            Friends   2                 At least 1 month but than 3 months   2                                     Never   5                                     Never   5                       About half the time   3                       At least 5-6 out of 10 times   4    Personal or family expenses (Health, education)   1           NaN   8
11908                                                NaN   0   South Africa   6                      More than 4 times   1       At least 1201 but less than 6400   3                                            Friends   2           At least 3 months but less than 6 months   3                       About half the time   3                       About half the time   3                          Most of the time   2                       At least 5-6 out of 10 times   4                                       I don't know   5           NaN   8
21602                                                NaN   0       Cameroon   1                         Plus de 4 fois   1                 Entre 10 001 et 59 000   2                                           Les amis   2                                         3 - 5 mois   3                                   Souvent   4                                   Souvent   4                                   Souvent   4                                      9 fois sur 10   2                                     Je ne sais pas   5           NaN   8

In [7]:
df[['credit_score', 'credit_score_category', 'lender_score', 'lender_score_category']]

       credit_score  credit_score_category  lender_score  lender_score_category
993             -70                      1           380                      2
8263            180                      1           -20                      1
13907           230                      1           430                      2
12918           -40                      1          -130                      1
22923           450                      2           510                      2
27414           130                      1           460                      2
7485            490                      2           520                      2
7890            310                      1           230                      1
3507            -30                      1            10                      1
785             610                      3           460                      2
6139            -40                      1          -120                      1
9367            420                      2           180                      1
17523           350                      1           470                      2
1114            480                      2           390                      2
23225           120                      1           300                      1
13581           460                      2           550                      2
1307            360                      2           410                      2
27348           440                      2           390                      2
1614             80                      1          -250                      1
2669            -90                      1           -90                      1
24930           610                      3           460                      2
21375           540                      2           610                      3
806             520                      2           260                      1
14791           520                      2           760                      5
23394           400                      2           600                      3
...             ...                    ...           ...                    ...
26582           390                      2           600                      3
28454           120                      1           510                      2
5792            370                      2           470                      2
24516           530                      2           380                      2
19266           270                      1           180                      1
13070           530                      2           310                      1
24215           420                      2           280                      1
20437           460                      2           460                      2
6457            220                      1           -30                      1
326             530                      2           270                      1
23953            40                      1          -170                      1
14586           300                      1           220                      1
10733           260                      1           -70                      1
28510           -40                      1          -110                      1
3630            530                      2           370                      2
7001            120                      1          -130                      1
9374            -40                      1           410                      2
10986          -110                      1           -70                      1
8051            340                      1            60                      1
5481            -90                      1          -390                      1
16589           700                      4           440                      2
23107           710                      4           560                      3
28864           490                      2           560                      3
17904            40                      1            60                      1
25870           450                      2           510                      2

[2938 rows x 4 columns]

In [6]:
# credit score
#
# risk              
#
# recipients = 20    
# interest = 22
# collateral = 23
#
# liqudity
#
# frequency = 18
# duration = 21
# amount = 19
#
# collection = 24
# usage = 26
# 
### lending environmnet columns and labels
dfc[['24','26','22','18','20','23','19','16','21','credit_score', 'credit_score_category']]

       24  26  22  18  20  23  19  16  21  credit_score  credit_score_category
0       3   3   3   2   3   2   2   3   3           550                      2
1       2   2   4   2   2   5   2   3   2           660                      4
2       2   3   2   2   2   2   2   3   2           540                      2
3       3   2   3   2   1   3   2   3   2           350                      1
4       2   3   2   2   3   3   1   3   3           530                      2
5       2   1   4   3   2   5   1   3   3           350                      1
6       2   2   3   3   2   2   3   3   2           470                      2
7       4   4   5   1   3   4   3   3   2           280                      1
8       3   2   3   2   3   2   3   3   3           470                      2
9       2   2   3   2   2   3   3   3   2           620                      3
10      3   2   2   2   2   3   3   3   2           420                      2
11      3   2   3   3   3   2   1   3   3           280                      1
12      3   2   3   3   2   2   2   3   2           350                      1
13      2   2   3   3   2   2   3   3   3           480                      2
14      3   4   4   2   2   4   2   3   3           450                      2
15      3   5   2   4   2   3   1   3   1           160                      1
16      3   4   2   3   2   3   2   3   2           210                      1
17      3   5   4   2   3   2   3   3   2           490                      2
18      2   2   3   3   2   3   2   3   3           520                      2
19      3   2   2   2   3   3   2   3   3           410                      2
20      3   3   3   2   3   3   3   3   3           630                      3
21      5   4   5   3   2   3   2   3   5           -40                      1
22      4   4   5   3   2   5   1   3   5           110                      1
23      2   5   3   2   2   2   2   3   2           540                      2
24      3   2   2   2   2   2   2   3   4           360                      2
...    ..  ..  ..  ..  ..  ..  ..  ..  ..           ...                    ...
29358   3   1   3   2   2   2   2   1   3           300                      1
29359   3   5   2   2   1   3   2   1   3           260                      1
29360   1   1   3   2   2   4   2   1   3           570                      3
29361   3   1   2   2   1   2   2   1   3            50                      1
29362   2   1   2   1   3   4   2   1   3           400                      2
29363   2   3   2   2   1   4   2   1   3           470                      2
29364   3   1   3   2   1   2   2   1   3           150                      1
29365   4   1   3   1   1   1   2   1   3           -90                      1
29366   4   3   1   3   1   3   2   1   3           -30                      1
29367   4   1   1   2   3   3   2   1   3           -40                      1
29368   3   3   4   1   2   1   2   1   3           590                      3
29369   4   1   3   1   3   2   2   1   5           100                      1
29370   2   1   3   2   2   3   2   1   4           470                      2
29371   2   1   3   2   3   3   2   1   3           460                      2
29372   1   1   2   2   2   4   2   1   3           470                      2
29373   4   5   2   1   2   4   2   1   4           210                      1
29374   2   3   3   2   3   3   2   1   3           710                      4
29375   4   1   3   2   3   1   2   1   3            30                      1
29376   3   1   4   2   2   3   2   1   3           390                      2
29377   1   1   2   1   1   4   2   1   2           340                      1
29378   4   1   3   1   1   2   2   1   2           -80                      1
29379   4   1   5   4   1   5   2   1   2           -70                      1
29380   3   1   4   2   1   4   2   1   2           240                      1
29381   3   3   5   1   2   5   2   1   3           740                      4
29382   4   1   5   3   2   5   2   1   3           120                      1

[29383 rows x 11 columns]

In [8]:
# lender evaluator columns and labels
dfc[['24','18','22','23','20','26','19','25','16','21','lender_score', 'lender_score_category']]

       24  18  22  23  20  26  19  25  16  21  lender_score  lender_score_category
0       3   2   3   2   3   3   2   4   3   3           480                      2
1       2   2   4   5   2   2   2   3   3   2           450                      2
2       2   2   2   2   2   3   2   3   3   2           610                      3
3       3   2   3   3   1   2   2   3   3   2           270                      1
4       2   2   2   3   3   3   1   3   3   3           510                      2
5       2   3   4   5   2   1   1   3   3   3           310                      1
6       2   3   3   2   2   2   3   3   3   2           470                      2
7       4   1   5   4   3   4   3   2   3   2           150                      1
8       3   2   3   2   3   2   3   4   3   3           460                      2
9       2   2   3   3   2   2   3   3   3   2           540                      2
10      3   2   2   3   2   2   3   2   3   2           470                      2
11      3   3   3   2   3   2   1   3   3   3           270                      1
12      3   3   3   2   2   2   2   3   3   2           350                      1
13      2   3   3   2   2   2   3   3   3   3           470                      2
14      3   2   4   4   2   4   2   3   3   3           360                      2
15      3   4   2   3   2   5   1   1   3   1           170                      1
16      3   3   2   3   2   4   2   3   3   2           360                      2
17      3   2   4   2   3   5   3   4   3   2           350                      1
18      2   3   3   3   2   2   2   3   3   3           430                      2
19      3   2   2   3   3   2   2   3   3   3           450                      2
20      3   2   3   3   3   3   3   3   3   3           480                      2
21      5   3   5   3   2   4   2   4   3   5          -140                      1
22      4   3   5   5   2   4   1   4   3   5           -50                      1
23      2   2   3   2   2   5   2   3   3   2           470                      2
24      3   2   2   2   2   2   2   2   3   4           490                      2
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..           ...                    ...
29358   3   2   3   2   2   1   2   3   1   3           470                      2
29359   3   2   2   3   1   5   2   4   1   3           230                      1
29360   1   2   3   4   2   1   2   3   1   3           630                      3
29361   3   2   2   2   1   1   2   3   1   3           350                      1
29362   2   1   2   4   3   1   2   3   1   3           590                      3
29363   2   2   2   4   1   3   2   4   1   3           420                      2
29364   3   2   3   2   1   1   2   3   1   3           320                      1
29365   4   1   3   1   1   1   2   4   1   3           110                      1
29366   4   3   1   3   1   3   2   3   1   3            30                      1
29367   4   2   1   3   3   1   2   3   1   3           260                      1
29368   3   1   4   1   2   3   2   3   1   3           480                      2
29369   4   1   3   2   3   1   2   3   1   5           280                      1
29370   2   2   3   3   2   1   2   3   1   4           570                      3
29371   2   2   3   3   3   1   2   4   1   3           550                      2
29372   1   2   2   4   2   1   2   3   1   3           660                      4
29373   4   1   2   4   2   5   2   4   1   4           160                      1
29374   2   2   3   3   3   3   2   3   1   3           560                      3
29375   4   2   3   1   3   1   2   3   1   3           230                      1
29376   3   2   4   3   2   1   2   3   1   3           410                      2
29377   1   1   2   4   1   1   2   3   1   2           540                      2
29378   4   1   3   2   1   1   2   3   1   2           100                      1
29379   4   4   5   5   1   1   2   4   1   2          -150                      1
29380   3   2   4   4   1   1   2   3   1   2           240                      1
29381   3   1   5   5   2   3   2   4   1   3           410                      2
29382   4   3   5   5   2   1   2   3   1   3            30                      1

[29383 rows x 12 columns]